require('aerial').setup({
	on_attach = function(bufnr)
		vim.keymap.set('n', '{', '<cmd>AerialPrev<CR>', { buffer = bufnr })
		vim.keymap.set('n', '}', '<cmd>AerialNext<CR>', { buffer = bufnr })
	end,

	backends = { 'lsp', 'treesitter', 'man', 'markdown' },
	filter_kind = false,
	icons = {
		Array = '󱡠',
		Boolean = '󰨙',
		Class = '󰆧',
		Constant = '󰏿',
		Constructor = '',
		Enum = '',
		EnumMember = '',
		Event = '',
		Field = '',
		File = '󰈙',
		Function = '󰊕',
		Interface = '',
		Key = '󰌋',
		Method = '󰊕',
		Module = '',
		Namespace = '󰦮',
		Null = '󰟢',
		Number = '󰎠',
		Object = '',
		Operator = '󰆕',
		Package = '',
		Property = '',
		String = '',
		Struct = '󰆼',
		TypeParameter = '󰗴',
		Variable = '󰀫',
		ArrayCollapsed = '󱡠 ',
		BooleanCollapsed = '󰨙',
		ClassCollapsed = '󰆧 ',
		ConstantCollapsed = '󰏿',
		ConstructorCollapsed = ' ',
		EnumCollapsed = ' ',
		EnumMemberCollapsed = ' ',
		EventCollapsed = ' ',
		FieldCollapsed = ' ',
		FileCollapsed = '󰈙 ',
		FunctionCollapsed = '󰊕 ',
		InterfaceCollapsed = ' ',
		KeyCollapsed = '󰌋 ',
		MethodCollapsed = '󰊕 ',
		ModuleCollapsed = ' ',
		NamespaceCollapsed = '󰦮 ',
		NullCollapsed = '󰟢',
		NumberCollapsed = '󰎠',
		ObjectCollapsed = ' ',
		OperatorCollapsed = '󰆕 ',
		PackageCollapsed = ' ',
		PropertyCollapsed = ' ',
		StringCollapsed = '',
		StructCollapsed = '󰆼 ',
		TypeParameterCollapsed = '󰗴',
		VariableCollapsed = '󰀫',
	},
	layout = {
		default_direction = 'right',
		max_width = { 40, 0.25 },
	},
	guides = {
		last_item = '└─ ',
		mid_item = '├─ ',
		nested_top = '│  ',
		whitespace = '   ',
	},
	keymaps = {
		['[['] = 'actions.prev',
		['[]'] = 'actions.prev_up',
		[']['] = 'actions.next_up',
		[']]'] = 'actions.next',
	},
	show_guides = true,
	update_events = 'CursorHold,CursorHoldI,InsertLeave',
})
vim.keymap.set('n', '<leader>at', '<cmd>AerialToggle!<CR>')
